//Pre-Basic Movement Test Header File

#pragma config(Motor,  motorA,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveStraight()
{
	motor[motorA] = 50;
	motor[motorB] = 50;
	sleep(1400);
}
