//ENGR 142: Project 3
//Team 57
//  Jillian Hestle, Emily Schott, Nicholas Vilbrandt, Tyler Stagge

//SATELLITE NAVIGATION PATH INTERPRETATION [PathInterpreter.m]
//
// This file contains all the necessary functions to read, interpret, and act
//  on the MRD code generated by PathGenerator.m

/*----------------------------FUNCTION  PROTOTYPES----------------------------*/
void readMRDstream(char* mrdFileName);

/*----------------------------FUNCTION DEFINITIONS----------------------------*/
void readMRDstream(char* mrdFileName, byte* fileStream)
{
	TFileHandle navFile;
	TFileIOResult isFileFailure;
	short nFileSize = 0;
	string iFileName = mrdFileName;
	//char* temp[200];
	//byte temp[200];

	OpenRead(navFile, isFileFailure, iFileName, nFileSize);
	//writeDebugStream("\nFile test\n");
	//writeDebugStream("Correct?: %d\n", isFileFailure);
	//writeDebugStream("Lines: %d\n", nFileSize);
	short i = 0;
	byte read = -1;
	for(i = 0; i < nFileSize; i++)
	{
		ReadByte(navFile,isFileFailure,read);
		//writeDebugStream("%c\n", read);
		fileStream[i] = read;
	}
		writeDebugStream("Correct?: %d\n", isFileFailure);

	Close(navFile, isFileFailure);
	//strcpy(fileStream, temp);
	//fileStream = &temp[0];
}
