//ENGR 142: Project 3
//Team 57
//  Jillian Hestle, Emily Schott, Nicholas Vilbrandt, Tyler Stagge

//SATELLITE NAVIGATION PATH INTERPRETATION [PathInterpreter.m]
//
// This file contains all the necessary functions to read, interpret, and act
//  on the MRD code generated by PathGenerator.m

/*----------------------------FUNCTION  PROTOTYPES----------------------------*/
void readMRDstream(char* mrdFileName);

/*----------------------------FUNCTION DEFINITIONS----------------------------*/
void readMRDstream(char* mrdFileName, byte* fileStream)
{
	TFileHandle navFile;
	TFileIOResult isFileFailure;
	short nFileSize = 0;
	string iFileName = mrdFileName;

	OpenRead(navFile, isFileFailure, iFileName, nFileSize);
	//writeDebugStream("\nFile test\n");
	//writeDebugStream("Correct?: %d\n", isFileFailure);
	//writeDebugStream("Lines: %d\n", nFileSize);
	short i = 0;
	byte read = -1;
	short numRealLines = 0;
	for(i = 0; i < nFileSize; i++)
	{
		ReadByte(navFile,isFileFailure,read);
		//writeDebugStream("%c\n", read);
		fileStream[i] = read;
		if((read == 68)||(read == 77)||(read == 82))//'D', 'M', or 'R'
		{
			numRealLines++;
		}
	}
	writeDebugStream("Correct?: %d\n", isFileFailure);
	Close(navFile, isFileFailure);

	writeDebugStream("Num real lines: %d\n", numRealLines);

	byte mrdCommands[30];
	short ic = 0;
	byte mrdParameters[30];
	short ip = 0;
	i = 1;
	//while(fileStream[i] != 42) //While not an asterisk
	while(i < (nFileSize-1))
	{
		if((fileStream[i] == 68)||(fileStream[i] == 77)||(fileStream[i] == 82))
		{
				mrdCommands[ic] = fileStream[i];
				writeDebugStream("Added command\n");
				ic++;
				i++;
				//char *tempStr = "";
				short tempNum = 0;
				short n = 0;
				while(fileStream[i] != 32)
				{
					//strcat(tempStr, fileStream[i])
					tempNum += (char)fileStream[i] * pow(10,n);
					n++;
					i++;
				}
				mrdParameters[ip] = tempNum;
				writeDebugStream("Added parameter\n");
				ip++;
		}
		else
			i++;
	}
	for(i = 0; i <= ic; i++)
	{
		writeDebugStream("%c %d\n", mrdCommands[i], mrdParameters[i]);
	}
}
